### ISSUE TITLE
We want something like a synergy score

### ISSUE THREAD

**Issue by vtbassmatt** [PDHdata/SmallFormats#45]
EDHrec calculates a card's synergy with respect to a commander as:
> (% decks this card is in for commander/theme) - (% decks this card is in for color identity) 

I haven't convinced myself that this is the score I want to use. Subtracting percentages with different bases doesn't seem mathematically sound. Consider the following universe of decks:
- There are two monowhite commanders, Holy Angel and Brave Knight. Each has 50 decks.
- There is one Azorius commander, Bird Guy. Bird Guy has 100 decks, we suppose because a white/blue identity has a larger variety in the card pool to draw from.
- A monowhite card called `Shiny Knight` shows up in every Brave Knight deck ( $50/50 = 100\\%$ ), but not in any Holy Angel or Bird Guy decks ( $50/200 = 25\\%$ ). Its synergy score $S$ with Brave Knight $S_{bk}$ is: $$S_{bk} = 100\\% - 25\\% = 75\\%$$
- A monowhite card called `Fast Bird` shows up in every Bird Guy deck ( $100/100 = 100\\%$ ), but none of the monowhite commanders' decks ( $100/200 = 50\\%$ ). Its synergy score with Bird Guy $S_{bg}$ is $$S_{bg} = 100\\% - 50\\% = 50\\%$$

This is hard to reason about. `Shiny Knight` and `Fast Bird` are, in a meaningful sense, bound equally tightly to their relevant commander (appearing in 100% of that commander's decks and nowhere else). But their synergy scores differ dramatically because of the larger variety in Bird Guy decks.

**Comment by aormiston** [comment]
One way to simplify the interpretation of this could be to remove the commander in question's decks from the comparison percentage.

For Brave Knight, it would look like:
50/50 Brave Knight
0/150 Other Mono White (Non Brave Knight)
100% - 0% = 100% synergy

For Bird Guy it would look like:
100/100 Bird Guy
0/100 Other Mono White
100% - 0% = 100% synergy 

This at least makes the interpretation for both consistent, despite having different total decks considered.

It also works for something like Sol Ring

Sol Ring
50/50 Brave Knight
150/150 Other Mono White
100%-100% = 0% Synergy 

What do you think?

**Comment by vtbassmatt** [comment]
I think you’re on to something here. Thank you! When I get a little spare time, I’ll see if this is straightforward to calculate from the existing tables or if there’s a bit more number crunching to do.

**Comment by aormiston** [comment]
Could be cool to do the same thing by subsetting to only decks that *could have* used the card as of the most recent "updated at" timestamp on the deck. 

In other words, "how many decks that have been updated since this card was printed have chosen to use it?"

Might help to avoid skewing a synergy score down due to a large number of stale decks.

**Comment by vtbassmatt** [comment]
This will be available soon. (The feature is dark-shipped and currently filing out initial scores.)
